apiVersion: v1
kind: Service
metadata:
  name: forum-service
spec:
  type: NodePort
  selector:
    app: forum
  ports:
    # - protocol: TCP
    - nodePort: 30000
      port: 3000
      targetPort: 3000